import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import './globals.css'
import Providers from '@/lib/Providers/Providers';
import { Toaster } from 'sonner';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  >
      <Providers>
        <AppRouterCacheProvider>
          <>
          <Toaster position="top-center" />
          {children}
          </>
        </AppRouterCacheProvider>
      </Providers>
      </body>
    </html>
  )
}
